"""Agent Studio-facing Yachiyo route handlers."""

from __future__ import annotations

from apps.bridge.routes.yachiyo_studio_agent_handlers import (
    attach_agent_skill,
    delete_agent,
    detach_agent_skill,
    get_agent,
    list_agents,
    save_agent,
    test_agent_model,
)
from apps.bridge.routes.yachiyo_studio_group_handlers import (
    get_group,
    get_group_run,
    list_group_runs,
    list_groups,
    save_group,
    start_group_run,
)
from apps.bridge.routes.yachiyo_studio_memory_handlers import (
    cancel_future_task,
    create_memory,
    delete_memory,
    list_future_tasks,
    list_memories,
    trigger_due_future_tasks,
    update_memory,
)
from apps.bridge.routes.yachiyo_studio_run_handlers import (
    approve_run_approval,
    cancel_run,
    delete_run,
    get_run_events,
    get_run_timeline,
    list_runs,
    read_run_artifact,
    reject_run_approval,
    rerun_run,
)
from apps.bridge.routes.yachiyo_studio_skill_handlers import (
    create_skill_folder,
    delete_skill,
    delete_skill_folder,
    import_skill,
    install_skill,
    list_skill_folders,
    list_skill_sources,
    list_skills,
    sync_native_skills,
    update_skill,
    update_skill_folder,
)
from apps.bridge.routes.yachiyo_studio_workflow_handlers import (
    delete_workflow,
    get_workflow,
    list_workflows,
    save_workflow,
    start_workflow_run,
)

__all__ = [
    "approve_run_approval",
    "attach_agent_skill",
    "cancel_future_task",
    "cancel_run",
    "create_memory",
    "create_skill_folder",
    "delete_agent",
    "delete_memory",
    "delete_run",
    "delete_skill",
    "delete_skill_folder",
    "delete_workflow",
    "detach_agent_skill",
    "get_agent",
    "get_group",
    "get_group_run",
    "get_run_events",
    "get_run_timeline",
    "get_workflow",
    "import_skill",
    "install_skill",
    "list_agents",
    "list_future_tasks",
    "list_group_runs",
    "list_groups",
    "list_memories",
    "list_runs",
    "list_skill_folders",
    "list_skill_sources",
    "list_skills",
    "list_workflows",
    "read_run_artifact",
    "reject_run_approval",
    "rerun_run",
    "save_agent",
    "save_group",
    "save_workflow",
    "start_group_run",
    "start_workflow_run",
    "sync_native_skills",
    "test_agent_model",
    "trigger_due_future_tasks",
    "update_memory",
    "update_skill",
    "update_skill_folder",
]
