"""Ports used by Yachiyo Agent facades.

The first phase deliberately depends on protocols instead of NativeRunEngine
internals so tests can use fake ports and existing runtime behavior remains
untouched.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import Any, Protocol


class RuntimePort(Protocol):
    def readiness(self) -> dict[str, Any]: ...

    def list_runnable_catalog(self) -> dict[str, Any]: ...

    def start_chat_task(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def get_task_snapshot(self, task_id: str) -> dict[str, Any]: ...

    def list_recent_tasks(self, conversation_id: str | None = None) -> list[dict[str, Any]]: ...

    def approve(
        self,
        approval_id: str,
        decision: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...

    def reject(self, approval_id: str, reason: str | None = None) -> dict[str, Any]: ...

    def cancel(self, task_id: str) -> dict[str, Any]: ...


class ChatTaskStarter(Protocol):
    def start_chat_task(self, request: dict[str, Any]) -> dict[str, Any] | None: ...


class StudioPort(Protocol):
    def list_agents(self) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def get_agent(self, agent_id: str) -> dict[str, Any]: ...

    def save_agent(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def delete_agent(self, agent_id: str) -> dict[str, Any]: ...

    def test_agent_model(self, agent_id: str) -> dict[str, Any]: ...

    def attach_skill(self, agent_id: str, skill_id: str) -> dict[str, Any]: ...

    def detach_skill(self, agent_id: str, skill_id: str) -> dict[str, Any]: ...

    def list_skills(self) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def update_skill(self, skill_id: str, request: dict[str, Any]) -> dict[str, Any]: ...

    def delete_skill(self, skill_id: str) -> dict[str, Any]: ...

    def list_skill_folders(self) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def create_skill_folder(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def update_skill_folder(self, folder_id: str, request: dict[str, Any]) -> dict[str, Any]: ...

    def delete_skill_folder(
        self,
        folder_id: str,
        delete_skills: bool = False,
    ) -> dict[str, Any]: ...

    def list_skill_sources(self) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def import_skill(self, source_path: str, folder_id: str | None = None) -> dict[str, Any]: ...

    def sync_native_skills(self) -> dict[str, Any]: ...

    def install_skill_command(self, command: str, folder_id: str | None = None) -> dict[str, Any]: ...

    def list_memories(
        self,
        include_deleted: bool = False,
        limit: int = 100,
    ) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def create_memory(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def update_memory(self, memory_id: str, request: dict[str, Any]) -> dict[str, Any]: ...

    def delete_memory(self, memory_id: str, reason: str | None = None) -> dict[str, Any]: ...

    def list_future_tasks(
        self,
        include_finished: bool = True,
        limit: int = 100,
    ) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def cancel_future_task(self, future_task_id: str, reason: str | None = None) -> dict[str, Any]: ...

    def trigger_due_future_tasks(
        self,
        now_epoch: float | None = None,
        limit: int = 20,
    ) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def start_agent_run(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def list_groups(self) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def get_group(self, group_id: str) -> dict[str, Any]: ...

    def save_group(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def start_group_run(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def list_group_runs(self, limit: int = 50) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def get_group_run(self, group_run_id: str) -> dict[str, Any]: ...

    def list_workflows(self) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def get_workflow(self, workflow_id: str) -> dict[str, Any]: ...

    def save_workflow(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def delete_workflow(self, workflow_id: str) -> dict[str, Any]: ...

    def start_workflow_run(self, request: dict[str, Any]) -> dict[str, Any]: ...

    def list_run_timelines(self, limit: int = 50) -> list[dict[str, Any]] | Mapping[str, Any]: ...

    def get_run_timeline(self, run_id: str) -> dict[str, Any]: ...

    def rerun_run(self, run_id: str) -> dict[str, Any]: ...

    def cancel_run(self, run_id: str) -> dict[str, Any]: ...

    def delete_run(self, run_id: str) -> dict[str, Any]: ...

    def approve_run_approval(self, run_id: str) -> dict[str, Any]: ...

    def reject_run_approval(self, run_id: str, reason: str | None = None) -> dict[str, Any]: ...

    def read_run_artifact(self, run_id: str, artifact_path: str) -> dict[str, Any]: ...

    def get_run_event_stream(
        self,
        run_id: str,
    ) -> Iterable[dict[str, Any]] | Mapping[str, Any]: ...
