"""Shared local path aliases for desktop file access entrypoints."""

from __future__ import annotations

import re


COMMON_DESKTOP_PATH_ALIASES: dict[str, str] = {
    "desktop": "~/Desktop",
    "desktopfolder": "~/Desktop",
    "桌面": "~/Desktop",
    "桌面文件夹": "~/Desktop",
    "桌面目录": "~/Desktop",
    "我的桌面": "~/Desktop",
    "downloads": "~/Downloads",
    "downloadsfolder": "~/Downloads",
    "downloadsdirectory": "~/Downloads",
    "下载": "~/Downloads",
    "下载列表": "~/Downloads",
    "下载记录": "~/Downloads",
    "下载页面": "~/Downloads",
    "下载文件夹": "~/Downloads",
    "下载目录": "~/Downloads",
    "我的下载": "~/Downloads",
    "documents": "~/Documents",
    "documentsfolder": "~/Documents",
    "documentsdirectory": "~/Documents",
    "文档": "~/Documents",
    "文档文件夹": "~/Documents",
    "文档目录": "~/Documents",
    "我的文档": "~/Documents",
    "文稿": "~/Documents",
    "文稿文件夹": "~/Documents",
    "文稿目录": "~/Documents",
    "我的文稿": "~/Documents",
    "我的文稿文件夹": "~/Documents",
    "我的文稿目录": "~/Documents",
    "pictures": "~/Pictures",
    "picturesfolder": "~/Pictures",
    "picturesdirectory": "~/Pictures",
    "图片文件夹": "~/Pictures",
    "图片目录": "~/Pictures",
    "我的图片": "~/Pictures",
    "我的图片文件夹": "~/Pictures",
    "照片文件夹": "~/Pictures",
    "照片目录": "~/Pictures",
    "我的照片": "~/Pictures",
    "我的照片文件夹": "~/Pictures",
    "moviesfolder": "~/Movies",
    "moviesdirectory": "~/Movies",
    "movies文件夹": "~/Movies",
    "movies目录": "~/Movies",
    "影片文件夹": "~/Movies",
    "影片目录": "~/Movies",
    "电影文件夹": "~/Movies",
    "电影目录": "~/Movies",
    "我的影片": "~/Movies",
    "我的电影": "~/Movies",
    "musicfolder": "~/Music",
    "musicdirectory": "~/Music",
    "music文件夹": "~/Music",
    "music目录": "~/Music",
    "音乐文件夹": "~/Music",
    "音乐目录": "~/Music",
    "我的音乐": "~/Music",
    "我的音乐文件夹": "~/Music",
    "publicfolder": "~/Public",
    "publicdirectory": "~/Public",
    "public文件夹": "~/Public",
    "public目录": "~/Public",
    "公共文件夹": "~/Public",
    "公共目录": "~/Public",
    "sharedfolder": "/Users/Shared",
    "shareddirectory": "/Users/Shared",
    "usersshared": "/Users/Shared",
    "共享文件夹": "/Users/Shared",
    "共享目录": "/Users/Shared",
    "用户共享文件夹": "/Users/Shared",
    "用户共享目录": "/Users/Shared",
    "home": "~",
    "homefolder": "~",
    "homedirectory": "~",
    "userfolder": "~",
    "userdirectory": "~",
    "家目录": "~",
    "主目录": "~",
    "个人主目录": "~",
    "我的主目录": "~",
    "用户文件夹": "~",
    "用户目录": "~",
    "个人文件夹": "~",
    "个人目录": "~",
    "currentfolder": ".",
    "currentdirectory": ".",
    "workingdirectory": ".",
    "workspace": ".",
    "currentworkspace": ".",
    "workspacefolder": ".",
    "workspacedirectory": ".",
    "currentproject": ".",
    "currentprojectfolder": ".",
    "currentprojectdirectory": ".",
    "currentrepo": ".",
    "currentrepository": ".",
    "currentrepofolder": ".",
    "currentrepositoryfolder": ".",
    "currentrepodirectory": ".",
    "currentrepositorydirectory": ".",
    "currentcodebase": ".",
    "currentcodebasefolder": ".",
    "currentcodebasedirectory": ".",
    "projectfolder": ".",
    "projectdirectory": ".",
    "当前目录": ".",
    "当前文件夹": ".",
    "当前工作区": ".",
    "工作区": ".",
    "工作区文件夹": ".",
    "工作区目录": ".",
    "当前项目": ".",
    "当前项目文件夹": ".",
    "当前项目目录": ".",
    "当前仓库": ".",
    "当前仓库文件夹": ".",
    "当前仓库目录": ".",
    "当前代码仓库": ".",
    "当前代码仓库文件夹": ".",
    "当前代码仓库目录": ".",
    "代码仓库文件夹": ".",
    "代码仓库目录": ".",
    "项目文件夹": ".",
    "项目目录": ".",
    "root": "/",
    "rootfolder": "/",
    "rootdirectory": "/",
    "根目录": "/",
    "根目录文件夹": "/",
    "系统根目录": "/",
    "tmp": "/tmp",
    "temp": "/tmp",
    "tmpfolder": "/tmp",
    "tmpdirectory": "/tmp",
    "tempfolder": "/tmp",
    "tempdirectory": "/tmp",
    "temporaryfolder": "/tmp",
    "temporarydirectory": "/tmp",
    "临时目录": "/tmp",
    "临时文件夹": "/tmp",
    "临时文件目录": "/tmp",
    "iclouddrive": "~/Library/Mobile Documents/com~apple~CloudDocs",
    "iclouddrivefolder": "~/Library/Mobile Documents/com~apple~CloudDocs",
    "iclouddrivedirectory": "~/Library/Mobile Documents/com~apple~CloudDocs",
    "我的iclouddrive": "~/Library/Mobile Documents/com~apple~CloudDocs",
    "icloud云盘": "~/Library/Mobile Documents/com~apple~CloudDocs",
    "icloud云盘文件夹": "~/Library/Mobile Documents/com~apple~CloudDocs",
    "icloud云盘目录": "~/Library/Mobile Documents/com~apple~CloudDocs",
    "我的icloud云盘": "~/Library/Mobile Documents/com~apple~CloudDocs",
    "applications": "/Applications",
    "applicationsfolder": "/Applications",
    "applicationfolder": "/Applications",
    "applicationsdirectory": "/Applications",
    "应用程序": "/Applications",
    "应用程序文件夹": "/Applications",
    "应用程序目录": "/Applications",
    "utilities": "/Applications/Utilities",
    "utilitiesfolder": "/Applications/Utilities",
    "utilitiesdirectory": "/Applications/Utilities",
    "utilityfolder": "/Applications/Utilities",
    "utilitydirectory": "/Applications/Utilities",
    "应用程序实用工具": "/Applications/Utilities",
    "应用程序实用工具文件夹": "/Applications/Utilities",
    "应用程序实用工具目录": "/Applications/Utilities",
    "实用工具": "/Applications/Utilities",
    "实用工具文件夹": "/Applications/Utilities",
    "实用工具目录": "/Applications/Utilities",
    "library": "~/Library",
    "libraryfolder": "~/Library",
    "librarydirectory": "~/Library",
    "资源库": "~/Library",
    "资源库文件夹": "~/Library",
    "资源库目录": "~/Library",
    "用户资源库": "~/Library",
    "用户资源库文件夹": "~/Library",
    "用户资源库目录": "~/Library",
    "trash": "~/.Trash",
    "trashfolder": "~/.Trash",
    "trashdirectory": "~/.Trash",
    "bin": "~/.Trash",
    "垃圾桶": "~/.Trash",
    "废纸篓": "~/.Trash",
    "回收站": "~/.Trash",
    "垃圾桶文件夹": "~/.Trash",
    "废纸篓文件夹": "~/.Trash",
    "回收站文件夹": "~/.Trash",
    "垃圾桶目录": "~/.Trash",
    "废纸篓目录": "~/.Trash",
    "回收站目录": "~/.Trash",
}

PLANNER_COMMON_PATH_MARKERS: tuple[tuple[str, str], ...] = (
    ("icloud云盘", "~/Library/Mobile Documents/com~apple~CloudDocs"),
    ("iclouddrive", "~/Library/Mobile Documents/com~apple~CloudDocs"),
    ("applicationsfolder", "/Applications"),
    ("应用程序文件夹", "/Applications"),
    ("实用工具文件夹", "/Applications/Utilities"),
    ("utilitiesfolder", "/Applications/Utilities"),
    ("下载文件夹", "~/Downloads"),
    ("下载目录", "~/Downloads"),
    ("下载列表", "~/Downloads"),
    ("下载记录", "~/Downloads"),
    ("下载页面", "~/Downloads"),
    ("downloads", "~/Downloads"),
    ("documentsfolder", "~/Documents"),
    ("我的文稿", "~/Documents"),
    ("文稿文件夹", "~/Documents"),
    ("desktopfolder", "~/Desktop"),
    ("桌面文件夹", "~/Desktop"),
    ("picturesfolder", "~/Pictures"),
    ("movies文件夹", "~/Movies"),
    ("movies目录", "~/Movies"),
    ("图片文件夹", "~/Pictures"),
    ("照片目录", "~/Pictures"),
    ("public文件夹", "~/Public"),
    ("public目录", "~/Public"),
    ("publicfolder", "~/Public"),
    ("公共文件夹", "~/Public"),
    ("moviesfolder", "~/Movies"),
    ("影片文件夹", "~/Movies"),
    ("music文件夹", "~/Music"),
    ("music目录", "~/Music"),
    ("musicfolder", "~/Music"),
    ("音乐目录", "~/Music"),
    ("libraryfolder", "~/Library"),
    ("资源库文件夹", "~/Library"),
    ("userdirectory", "~"),
    ("用户目录", "~"),
    ("个人主目录", "~"),
    ("家目录", "~"),
    ("共享文件夹", "/Users/Shared"),
    ("sharedfolder", "/Users/Shared"),
    ("当前工作区", "."),
    ("当前项目", "."),
    ("当前仓库", "."),
    ("项目目录", "."),
    ("垃圾桶", "~/.Trash"),
    ("回收站", "~/.Trash"),
    ("trashfolder", "~/.Trash"),
    ("临时目录", "/tmp"),
    ("根目录", "/"),
)


def common_desktop_path_alias(value: str) -> str:
    return COMMON_DESKTOP_PATH_ALIASES.get(compact_path_alias(value), "")


def common_desktop_path_marker(text: str) -> str:
    normalized = compact_path_alias(text)
    for marker, path in PLANNER_COMMON_PATH_MARKERS:
        if marker in normalized:
            return path
    return ""


def compact_path_alias(value: str) -> str:
    return re.sub(r"[\s._-]+", "", str(value or "").strip().lower())
